### ISSUE TITLE
Attempt to remember and re-test issues from previous github 

### ISSUE THREAD

**Issue by HeroponRikiBestest** [ares-emulator/ares#22]
This issue will be fairly disorganized, as I try and remember as much as possible that went wrong originally. As I re-test, things will be split into individual issues
Mega Drive:
- [x] Every Treasure game has issues with the 3d aspects https://github.com/ares-emulator/ares/issues/176
- [x] Music in adventures of batman in Robin cuts out at the stage one boss https://github.com/ares-emulator/ares/issues/114
- [x] Unable to start new game in Japanese version of Super Hydlide
- [x] Text and some other issues in Landstalker https://github.com/ares-emulator/ares/issues/117
- [x] Something is still wrong with musha, possibly only on regular profile?
- [x] Magical Hat no Buttobi Turbo! Daibouken had a weird issue where your quickly turning around animation would make a row of tiles invisible, possibly only on regular profile?

Mega CD
- [x] A lot of different issues with After Armageddon Gaiden on both profiles
- [ ] Some discs aren't recognized, don't remember which
Unsure how to test this
- [ ] Battletech Grey Death Legion has issues https://github.com/ares-emulator/ares/issues/438
- [ ] Load times and track switches take too long on all games, CD music doesn't seem to loop either
Unsure of the best way to test this, will try another time
- [x] Arcus 1.2.3 might still have issues, don't remember if everything was fixed
- [ ] AX-101 only works on some BIOSes. https://github.com/ares-emulator/ares/issues/441
- [x] Something is still wrong with Robo Aleste

32x
- [x] That golfing game flashes during the intro

Pc Engine
- [x] Valkryie no Densetsu has an issue where the camera doesn't follow you, and the HUD follows your character 
- [ ] HUD issues with strip fighter 2
- [ ] Issues during curtain scene in Wonder Momo https://github.com/ares-emulator/ares/issues/442

Pc Engine CD
- [ ] Asuka 120% has a multitude of issues on both profiles https://github.com/ares-emulator/ares/issues/443
- [ ] Currently no support for games express cards, and by extension their CD games https://github.com/ares-emulator/ares/issues/444
- [ ] A huge amount of games with visual scenes/sequences are misaligned, have garbage, etc, depending on the profile
Unsure how to test this atm

Playstation
- [ ] Pingu doesn't work 

Other
- [x] Shin Megami Tensei dungeons are really broken on either the pc engine cd or mega cd version, don't remember which, possibly both
- [ ] Support for more bootleg mega drive games?
- [ ] MSX needs support for actual BIOSes and floppy disks, maybe tapes too

**Comment by birdybro** [comment]
Just adding to the list, I'm fully aware that the Genesis emu in Ares isn't really a stable emulator yet.

Here's some Genesis/Mega Drive bugs/issues I've observed in testing with ares-nightly 2021-08-21 (on windows 11 preview x64):

* Castlevania Bloodlines Music is wrong: anytime the sustained notes do a tremolo, it's a different speed and a different tone.
* Ecco the Dolphin has multiple graphical glitches during the intro, the  framerate in the game itself begins to suffer. The sound effect for dashing is very inaccurate, way too high pitched. ADPCM playing too fast possibly?
* Thunder Force IV all graphics and Sega logo even are very corrupted and game is unplayable as a result.
* Shining Force - Audio glitches when audio overlaps with characters talking and you holding down c button. Skipping/fast forward text also has an unusually longer delay per line.
*  Shining Force II - Text boxes and scrolling text appear to cause graphical glitches at the top of the screen.
* Phantasy Star IV - Randomly the music hiccups here and there, possibly correlated to loading in between screens and stuff like that. In battle audio stutters and starts to slow down during flashing animations of characters attacking. Example, Alys' Vortex and Chaz's double slash attack, the last slash sound effect and animation is delayed.
* Most games that have very active sound and music combined with lots of rapid graphics seem to be struggling to keep up overall.

**Comment by Shideravan** [comment]
I cannot reproduce the "Magical Hat no Buttobi Turbo! Daibouken" bug. Maybe was already fixed?
![image](https://user-images.githubusercontent.com/12163923/131069755-244e8fe9-de54-40f5-bba8-56ac438ca252.png)

**Comment by Shideravan** [comment]
I also tested all the treasure games too and didn't find any bugs. Even in McDonalds game level select screen.
![image](https://user-images.githubusercontent.com/12163923/131073085-177c95b4-bb38-4db7-8295-fab93bcd6660.png)

Treasure's games tested:
* Alien Soldier
* Dynamite Headdy
* Gunstar Heroes
* Light Crusader
* McDonald's Treasure Land Adventure
* Yū Yū Hakusho Makyō Tōitsusen

**Comment by HeroponRikiBestest** [comment]
The garbage seems to be gone in all of the Treasure games, and the issue with Magical Hat seems to be fixed. However, now both profiles exhibit issues in the Mcdonalds 3d test screen (this article shows how to enter it https://www.polygon.com/22412468/mcdonalds-treasure-land-adventure-creepy-easter-egg-secret-cheat-masato-maegawa). Will now test the remaining issues.

**Comment by Shideravan** [comment]
What do you mean with "profiles"?

**Comment by LukeUsher** [comment]
> What do you mean with "profiles"?

for most systems, ares contains both a 'performance' profile, and an 'accuracy' profile. 

Generally, the accuracy profile is not designed for end-users, but can be activated on self-compiled builds for debugging/testing purposes.

**Comment by Shideravan** [comment]
Are you sure that the issue in Strip Fighter II isn't caused by the overscan area?
![image](https://user-images.githubusercontent.com/12163923/132721028-ff22fbc4-cc20-410f-aa63-2b265ed0db5b.png)

Also, the same issue happens in MAME
![image](https://user-images.githubusercontent.com/12163923/132720938-bc5292a2-9ab1-48d0-ac6f-0d158a65550b.png)

**Comment by HeroponRikiBestest** [comment]
The HUD issue I was experiencing at the time was something different. It seems to be fixed now, but I need to test it myself.

**Comment by Shideravan** [comment]
> The garbage seems to be gone in all of the Treasure games, and the issue with Magical Hat seems to be fixed. However, now both profiles exhibit issues in the Mcdonalds 3d test screen (this article shows how to enter it https://www.polygon.com/22412468/mcdonalds-treasure-land-adventure-creepy-easter-egg-secret-cheat-masato-maegawa). Will now test the remaining issues.

Ok, I can reproduce this. I created an issue for this #176

**Comment by Shideravan** [comment]
> Just adding to the list, I'm fully aware that the Genesis emu in Ares isn't really a stable emulator yet.
> 
> Here's some Genesis/Mega Drive bugs/issues I've observed in testing with ares-nightly 2021-08-21 (on windows 11 preview x64):
> 
> * Castlevania Bloodlines Music is wrong: anytime the sustained notes do a tremolo, it's a different speed and a different tone.
> * Ecco the Dolphin has multiple graphical glitches during the intro, the  framerate in the game itself begins to suffer. The sound effect for dashing is very inaccurate, way too high pitched. ADPCM playing too fast possibly?
> * Thunder Force IV all graphics and Sega logo even are very corrupted and game is unplayable as a result.
> * Shining Force - Audio glitches when audio overlaps with characters talking and you holding down c button. Skipping/fast forward text also has an unusually longer delay per line.
> * Shining Force II - Text boxes and scrolling text appear to cause graphical glitches at the top of the screen.
> * Phantasy Star IV - Randomly the music hiccups here and there, possibly correlated to loading in between screens and stuff like that. In battle audio stutters and starts to slow down during flashing animations of characters attacking. Example, Alys' Vortex and Chaz's double slash attack, the last slash sound effect and animation is delayed.
> * Most games that have very active sound and music combined with lots of rapid graphics seem to be struggling to keep up overall.

I'm unable to reproduce all of these glitches in most recent ares version.
Were all of them fixed as of the latest nightly version?
Could you retest with the latest nightly version and verify if all of them are fixed?

**Comment by Shideravan** [comment]
Using ares 3ca1f9e

I cannot reproduce any issues in the following games:
* After Armageddon Gaiden (Sega CD)
* Asuka 120% (PC Engine CD)
* Shin Megami Tensei (Sega CD)

Also, are you sure there's Momoko 120% for PC Engine CD? I'm just aware of Famicon and arcade versions.

**Comment by birdybro** [comment]
@Shideravan 

1. Castlevania notes are still inaccurate. I tried both v123 and the latest nightly and the behavior is still happening.
[Ares Castlevania clips.zip](https://github.com/ares-emulator/ares/files/7321730/Ares.Castlevania.clips.zip)  
Compared to recordings taken from original hardware:  
https://www.youtube.com/watch?v=d9Fxw8IcYK4  
https://www.youtube.com/watch?v=_VQz2ZPbltw  
Is the relatively recently discovered Timer B Konami game behavior implemented for the ym2612? @Ace9921 is very knowledgeable on that subject so tagging him here.  
I probably am using the wrong terminology, it might be that the vibratos are incorrect as opposed to the tremolos? Not sure, but this is probably the relevant component to look at --> https://github.com/ares-emulator/ares/blob/master/ares/component/audio/ym2612/constants.cpp
2. Ecco the Dolphin's issues are resolved.
3. Thunder Force IV's issues are resolved.
4. Shining Force Issues are resolved.
5. Shining Force II Issues are resolved.
6. Phantasy Star IV the audio still sounds like it occasionally pauses for a split second to catch up. Is this core syncing to video or syncing to audio? Other than that new thing I noticed (probably was there all along), the observed behavior I previously mentioned is resolved.

Thanks!

**Comment by LukeUsher** [comment]
@HeroponRikiBestest any chance you can retest against the latest master?

I also modified the first post into a check-list so we can tick things off as they are resolved

**Comment by HeroponRikiBestest** [comment]
Yeah, sorry about that. I'll try and go through this again.

**Comment by HeroponRikiBestest** [comment]
I've tested all the mega drive/cd/32x issues and marked the ones that have been resolved. I'll do the pc engine ones tomorrow, as I don't have access to my pc engine dumps this second.

**Comment by HeroponRikiBestest** [comment]
Finished going through all issues, although I marked the few that were more broad I'd need extensive testing to confirm.

**Comment by HeroponRikiBestest** [comment]
Is it worth separating these into their own individual issues now that I've tested them? Or should I keep them on this meta issue.

**Comment by remutro** [comment]
Remaining issues are known, have associated issues, are enhancements that are known and will get added, or are documented in our compatibility database (which didn't exist at the time of this issue). This can be closed now and individual issues will be tracked accordingly.

**Comment by HeroponRikiBestest** [comment]
No longer necessary due to the above.
